<div id="view-content">
	<div>
		<!-- error message start -->
		<?php
			if(isset($this->errorMessage))
				echo $this->errorMessage;
		?>
		<!-- error message end -->
	</div>
	<div>
		<!-- form start -->
		<form method=post >
			<label>OriginPassword</label>
			<input type ="password" name ="OriginPassword">
			<label>NewPassword1</label>
			<input type ="password" name ="NewPassword1">
			<label>NewPassword2</label>
			<input type ="password" name ="NewPassword2">
			<input type ="submit" name="submit" value="submit">
		</form>
		<!-- form end  -->
	</div>
</div>