<div id="panel-content">
	<?php
		
		if($this->panel_user_name)
		{
			echo "Welcome!  ";
			if($this->panel_user_power)
			{
				echo '<a href="/'.$this->panel_user_power.'">'.$this->panel_user_power.'</a>   ' ;
			}
			else
				echo '<a href="/User">NormalUser</a>   ';
			echo $this->panel_user_name,'   ';
			echo '<a href="/Logout">Log out</a>';
		}
		else
		{
			echo '<a href="/Login">Log in</a>    ';
			
			echo '<a href="/Register">Register</a>    ';
			echo '<a href="/Login?admin=true">Admin Login</a>';
		}
	?>
</div>