<div id="view-content">
	<div id="title"><h2 class="title">
		<font size=6px color=#333399>用户信息</font>
	</h2></div>
	<div id="abc"></div>
	<div>
	<!-- errormsg -->
	<?php
		echo $this->errormsg;
	?>
	</div>
	<div>
	<div id="left">
		<div>
		<!-- user_id -->
		用户ID:
		<?php
			echo $this->user_id;
		?>
		</div>
		<div>
		<!-- user_name -->
		用户名:
		<?php
			echo $this->user_name;
		?>
		</div>
	</div>
	<div id="right">
		<div>
		<!-- user_acc_count -->
		答题成功数:
		<?php
			echo $this->user_acc_count;
		?>
		</div>
		<div>
		答题尝试数:
		<!-- user_submit_count -->
		<?php
			echo $this->user_submit_count;
		?>
		</div>
		<div>
		答题成功率:
		<!-- user_acc_rate -->
		<?php
			echo $this->user_acc_rate;
		?>
		</div>
	</div>
	</div>
	<div>
	&nbsp;
	</div>
	<div>
	<!-- acc_code_list -->
	<table id="mytable" cellspacing="0" 	>
		<caption></caption>
			<tr>
				<th scope="col" width=8%>流水号</th>
				<th scope="col" width=10%>用户名</th>
				<th scope="col" width=10%>题目ID</th>
				<th scope="col" width=11%>结果</th>
				<th scope="col" width=10%>内存</th>
				<th scope="col" width=10%>时间</th>
				<th scope="col" width=7%>语言</th>
				<th scope="col" width=10%>代码长度</th>
				<th scope="col" width=13%>提交时间</th>
			</tr>
	<?php
		if($this->acc_code_list)
		{
			$line=1;
			foreach($this->acc_code_list as $key2=>$row)
			{
				echo "<tr>";
				foreach($row as $key=>$coloum)
				{
					if(!is_integer($key))
					{
						if($line%2)
							echo '<th scope="row" class="spec">';
						else
							echo '<th scope="row"  class="specalt">';
							
						if($key =='user_name')
						{
							if($coloum!='NULL')
							{
								echo '<a href="/User/Userinfo?user_name=';
								echo str_replace("\n","<br>",stripslashes($coloum));
								echo '">'.str_replace("\n","<br>",stripslashes($coloum)).'</a>';
							}
							else
								echo $coloum;
						}
						else if($key =='run_pid')
						{
							if($coloum!='NULL')
							{
								echo '<a href="/Browse-Problem/Detail?p_id=';
								echo str_replace("\n","<br>",stripslashes($coloum));
								echo '">'.str_replace("\n","<br>",stripslashes($coloum)).'</a>';
							}
							else
								echo $coloum;
						}
						else if($key =='run_mcost')
						{
							if($coloum!='NULL')
							{
								echo str_replace("\n","<br>",stripslashes($coloum));
								echo ' KB';
							}
							else
								echo $coloum;
						}
						else if($key =='run_tcost')
						{
							if($coloum!='NULL')
							{
								echo str_replace("\n","<br>",stripslashes($coloum));
								echo ' MS';
							}
							else
								echo $coloum;
						}
						else if($key =='run_codel')
						{
							if($coloum!='NULL')
							{
								echo str_replace("\n","<br>",stripslashes($coloum));
								echo ' B';
							}
							else
								echo $coloum;
						}
						else
							echo str_replace("\n","<br>",stripslashes($coloum));
							
						echo "</th>";
					}
				}
				echo "</tr>";
				$line++;
			}
		}else
			echo '<tr>
				<th scope="row" class="spec">NULL</th>
				<th scope="row" class="spec">NULL</th>
				<th scope="row" class="spec">NULL</th>
				<th scope="row" class="spec">NULL</th>
				<th scope="row" class="spec">NULL</th>
				<th scope="row" class="spec">NULL</th>
				<th scope="row" class="spec">NULL</th>
				<th scope="row" class="spec">NULL</th>
				<th scope="row" class="spec">NULL</th>
				</tr>';
	?>
	</table>
	</div>
</div>
