<div id="view-content">
	<div>
	<!-- errormsg -->
	<?php
		echo $this->errormsg;
	?>
	</div>
	<div>
	<!-- user_id -->
	<?php
		echo $this->user_id;
	?>
	</div>
	<div>
	<!-- user_name -->
	<?php
		echo $this->user_name;
	?>
	</div>
	<div>
	<!-- user_acc_count -->
	<?php
		echo $this->user_acc_count;
	?>
	</div>
	<div>
	<!-- user_submit_count -->
	<?php
		echo $this->user_submit_count;
	?>
	</div>
	<div>
	<!-- user_acc_rate -->
	<?php
		echo $this->user_acc_rate;
	?>
	</div>
	<div>
	<!-- acc_code_list -->
	<table id="mytable" cellspacing="0" 	>
		<caption></caption>
			<tr>
				<th scope="col" width=8%>Run ID</th>
				<th scope="col" width=10%>User</th>
				<th scope="col" width=6%>Problem</th>
				<th scope="col" width=20%>Result</th>
				<th scope="col" width=7%>Memory</th>
				<th scope="col" width=7%>Time</th>
				<th scope="col" width=7%>Language</th>
				<th scope="col" width=7%>Code Length</th>
				<th scope="col" width=17%>Submit Time</th>
			</tr>
	<?php
		if($this->acc_code_list)
		{
			$line=1;
			foreach($this->acc_code_list as $key2=>$row)
			{
				echo "<tr>";
				foreach($row as $key=>$coloum)
				{
					if(!is_integer($key))
					{
						if($line%2)
							echo '<th scope="row" class="spec">';
						else
							echo '<th scope="row"  class="specalt">';
							
						if($key =='user_name')
						{
							if($coloum!='NULL')
							{
								echo '<a href="/User/Userinfo?user_name=';
								echo str_replace("\n","<br>",stripslashes($coloum));
								echo '">'.str_replace("\n","<br>",stripslashes($coloum)).'</a>';
							}
							else
								echo $coloum;
						}
						else if($key =='run_pid')
						{
							if($coloum!='NULL')
							{
								echo '<a href="/Browse-Problem/Detail?p_id=';
								echo str_replace("\n","<br>",stripslashes($coloum));
								echo '">'.str_replace("\n","<br>",stripslashes($coloum)).'</a>';
							}
							else
								echo $coloum;
						}
						else
							echo str_replace("\n","<br>",stripslashes($coloum));
							
						echo "</th>";
					}
				}
				echo "</tr>";
				$line++;
			}
		}else
			echo '<tr>
				<th scope="row" class="spec">NULL</th>
				<th scope="row" class="spec">NULL</th>
				<th scope="row" class="spec">NULL</th>
				<th scope="row" class="spec">NULL</th>
				<th scope="row" class="spec">NULL</th>
				<th scope="row" class="spec">NULL</th>
				<th scope="row" class="spec">NULL</th>
				<th scope="row" class="spec">NULL</th>
				<th scope="row" class="spec">NULL</th>
				</tr>';
	?>
	</table>
	</div>
</div>