
<div id="view-content">

	
	<div>
		<!-- errormsg -->
		<?php 
			if(isset($this->errormsg))
				echo $this->errormsg;
		?>
		<!-- errormsg end -->
	</div>
	<div><h2 class="title">
		<a herf="#"> 
		<b>
		<!-- p_title start -->
		<?php 
			if(isset($this->p_title))
				echo $this->p_title;
		?>
		<!-- p_title end -->
		</b>
		</a>
	</h2>
	</div>
	<div id="top">
	<div id="timelimit">
		<a>时间限制: </a>
		<!-- p_tlimt start -->
		<?php 
			if(isset($this->p_tlimt))
				echo $this->p_tlimt;
		?>
		<a>ms</a>
		<!-- p_tlimt end -->
	</div>
	<div id="memorylimit">
		<a>内存限制:</a>
		<!-- p_mlimt start -->
		
		<?php 
			if(isset($this->p_mlimt))
				echo $this->p_mlimt;
		?>
		<a>KB</a>
		<!-- p_mlimt end -->
	</div>
	</div>
	<div>
		<!-- p_disc start -->
		<?php 
			if(isset($this->p_disc))
				echo $this->p_disc;
		?>
		<!-- p_disc end -->
	</div>
	<div>
		<!-- p_sample_input start -->
		<?php 
			if(isset($this->p_sample_input))
				echo $this->p_sample_input;
		?>
		<!-- p_sample_input end -->
	</div>
	<div>
		<!-- p_sample_output start -->
		<?php 
			if(isset($this->p_sample_output))
				echo $this->p_sample_output;
		?>
		<!-- p_sample_output end -->
	</div>
	<div>
		<!-- p_source start -->
		<?php 
			if(isset($this->p_source))
				echo $this->p_source;
		?>
		<!-- p_source end -->
	</div>
	<div>
		<!-- p_input_tips start -->
		<?php 
			if(isset($this->p_input_tips))
				echo $this->p_input_tips;
		?>
		<!-- p_input_tips end -->
	</div>
	<div>
		<!-- p_output_tips start -->
		<?php 
			if(isset($this->p_output_tips))
				echo $this->p_output_tips;
		?>
		<!-- p_output_tips end -->
	</div>
	<div>
		<!-- p_hint start -->
		<?php 
			if(isset($this->p_hint))
				echo $this->p_hint;
		?>
		<!-- p_hint end -->
	</div>
	<div>
		<!-- submit start -->
		<?php
		if(!isset($this->errormsg))
		echo '
		<form  action="/Submit-Code" method="get">
				<input type="hidden" value="',$this->p_id,'"name="p_id"/>
				<input type="submit" value="提交代码"/>
		</form>';
		?>
		<!-- submit end -->
	</div>
</div>