<div id="view-content">
	<div id="title"><h2 class="title">
		<font size=6px color=#333399>题目列表</font>
	</h2></div>
	<div id="abc"></div>
	
	<div>
	<!-- 页码 -->
	<?php
		if($this->Page_Num)
		{
			for($i=1;$i<=$this->Page_Num;$i++)
			{
				echo '<a class="ui-base-button" href="/Browse-Problem?page=',$i,'"> <span>第',$i,'页</span> </a>';
				//echo '<a href="/Browse-Problem?page=',$i,'">',$i,'</a> ';
			}
		}
	?>
	</div>
			
	<table id="mytable" cellspacing="0" 	>
		<caption></caption>
		<tr>
			<th scope="col" width=15%>题目ID</th>
			<th scope="col" width=45%>题目标题</th>
			<th scope="col" width=15%>答题成功数</th>
			<th scope="col" width=15%>答题尝试数</th>
		</tr>
	<?php
		if($this->Result)
		{
			$line=1;
			foreach($this->Result as $key2=>$row)
			{
				echo "<tr>";
				foreach($row as $key=>$coloum)
				{
					if(is_integer($key))
					{	
						if($line%2)
							echo '<th scope="row" class="spec">';
						else
							echo '<th scope="row" class="specspecalt">';
						if($key==1)
						{
							if($coloum!='NULL')
							{
								echo '<a href="/Browse-Problem/Detail?p_id=';
								echo $row['p_id'].'">'.stripslashes($coloum);
								echo '</a>';
							}
							else
								echo 'NULL';
						}
						else
							echo str_replace("\n","<br>",stripslashes($coloum));						
						echo "</th>";
					}
				}
				echo "</tr>";
				$line++;
			}
		}
	?>
	</table>
</div>