<div id="view-content">

		<table cellpadding="1" cellspacing="1" bgcolor="#DCDCDC" border="0" align="center" width="100%" bordercolor=#ffffff>
					<tr>
						<td class="b" width=15%>
							题目ID
							<td class="b"width=45%>题目标题</td>
							<td class="b" width=15%>答题成功数</td>
							<td class="b" width=15%>答题尝试数</td>
							<tr>
		<?php
		if($this->Result)
		{
			foreach($this->Result as $row)
			{
				echo "<tr>";
				foreach($row as $key=>$coloum)
				{
					if(is_integer($key))
					{	
						echo "<th class='b'>";
						if($key==0)
						{
							echo '<a href="/Browse-Problem/Detail?p_id=';
							echo stripslashes($coloum).'">'.stripslashes($coloum);
							echo '</a>';
						}
						else
							echo str_replace("\n","<br>",stripslashes($coloum));						
						echo "</th>";
					}
				}
				echo "</tr>";
			}
		}
		?>
		</table>
</div>
<?php
		echo $this->formProblem;
?>
