<div id="page">
	<div id="submit">
		<div id="submittitle">
			<h2 class="title"><a herf="#"><b>Submit Your Solition Via Web</b></a><h2>
			
			<?php
				echo $this->formCode;
			/*
			<h3>Problem ID: <input type="text" id="s" name="s" value=""></h3>
			<h3>Language:
				<select size=1 name=language>
					<option value=0>G++</option>
					<option value=1 selected>GCC</option>
					<option value=2>Java</option>
					<option value=3>Pascal</option>
					<option value=4>C++</option>
					<option value=5>C</option>
					<option value=6>Fortran</option>
				</select>
			</h3>

			<h3>sourse:</h3>
			 <br>
		<textarea rows=20 name=source cols=110></textarea><br>
		<input type=submit value=Submit name=submit accesskey=s><input type=reset value=Reset name=reset>
			*/
			?>
		</div>
	</div>
	
	<div style="clear: both;">&nbsp;</div>
</div>