<div id="view-content">
	<div id="title"><h2 class="title">
		<font size=6px color=#333399>上传代码</font>
	</h2></div>
	<div id="abc"></div>
	<div id="submit">
		<div id="submittitle">
		<!-- code form start -->
			<?php
				if(isset($this->errormsg))
				{
					if($this->errormsg=="Succeed")
						echo '<script type="text/javascript">window.location.href="Online-Status";</script>';
					else
					{
						echo $this->errormsg;
						echo '<br><a href="javascript:history.go(-1);">return</a>';
					}
					/*echo '<div>';
					echo '<a href="/Browse-Problem">Return Problem List</a>   ';
					echo '</div>';
					echo '<div>';
					echo '<a href="/Online-Status">Check Online Status</a>';
					echo '</div>';*/
					
				}	
				else
				{
					echo '</div>';
					echo '<div>';
					echo $this->formCode;
					echo '</div>';
				}
			?>
		<!-- code form end -->
		</div>
		<script type="text/javascript">
var onTextareaKeydown = function(e){
	if(e.keyCode == 9){
		e.preventDefault();
		var start = this.selectionStart, end = this.selectionEnd;
		var text = this.value;
		var tab = '    ';
		text = text.substr(0, start) + tab + text.substr(start);
		this.value = text;
		this.selectionStart = start + tab.length;
		this.selectionEnd = end + tab.length;
	}
}
document.getElementById('CodeSource').onkeydown = onTextareaKeydown;
</script>
	</div>
</div>