<div id="content">
		<div class="post">
			<h2 class="title"><b>Welcome to </b>ECUST JudgeOnline </h2>
            <p class="welcome">HI<b></b></p><br><br>
			<div class="entry">
				<p>大家好，欢迎来到ECUST在线答题系统，在这儿，你可以找到丰富的海量题库，供你测试你的解题能力。当然咯，首先你得注册一个永久免费的账号，仔细阅读题目要求后，享受解题带来的乐趣吧~~~~
				</p>
			</div>
		</div>
	</div>
	<!-- end content -->
	<!-- start sidebar -->

	<div id="sidebar">
		<ul>
			<li id="login">
				<h2><b class="text1">User</b></h2>
				<!-- result start -->
				<?php
					echo $this->result;
				?>
				<!-- result end -->
			</li>
			<li>
				
		</ul>

	</div>
	<!-- end sidebar -->
	<div style="clear: both;">&nbsp;</div>