<div id="content">
		<div class="post">
			<h2 class="title"><b>Welcome to </b>ECUST JudgeOnline </h2>
            <p class="welcome">HI<b></b></p>
			<div class="entry">
				<p>Problem Set is the place where you can find large amount of problems from different programming contests.Online Judge System allows you to test your solution for every problem.

  First of all, read carefully Frequently Asked Questions.
  Then, choose a problem, solve it and submit your solution.

  If you want to publish your problems or setup your own online contest, just write to us.
 </p>
			</div>
		</div>
	</div>
	<!-- end content -->
	<!-- start sidebar -->

	<div id="sidebar">
		<ul>
			<li id="login">
				<h2><b class="text1">User</b></h2>
				<!-- result start -->
				<?php
					echo $this->result;
				?>
				<!-- result end -->
			</li>
			<li>
				
		</ul>

	</div>
	<!-- end sidebar -->
	<div style="clear: both;">&nbsp;</div>