<div id="view-content">
	<div id="title"><h2 class="title">
		<font size=6px color=#333399>更改密码</font>
	</h2></div>
	<div id="abc"></div>
	<div>
		<!-- error message start -->
		<?php
			if(isset($this->errorMessage))
			{
				echo $this->errorMessage;
				echo '&nbsp&nbsp<a href="/User">return</a>';
				//echo '<br>';
			}
		?>
		<!-- error message end -->
	</div>
	<div id="password">
			温馨提示：密码首字母必须是字母，长度在6到18个字符之间 
	</div>
	<div>
		<!-- form start -->
		<form method=post >
			<label>原密码</label>
			<br>
			<input type ="password" name ="OriginPassword">
			<br>
			<label>新密码</label>
			<br>
			<input type ="password" name ="NewPassword1">
			<br>
			<label>重复一遍</label>
			<br>
			<input type ="password" name ="NewPassword2">
			<br>
			<input type ="submit" name="submit" value="提交">
		</form>
		<!-- form end  -->
	</div>
</div>