<div id="view-content">
	<div>
		<!-- error message start -->
		<?php
			if(isset($this->errorMessage))
			{
				echo $this->errorMessage;
				echo '  <a href="/User">return</a>';
			}
		?>
		<!-- error message end -->
	</div>
	<div>
		Password initial must be charactor, not shorter than 6 letters and not longer than 18 letters 
	</div>
	<div>
		<!-- form start -->
		<form method=post >
			<label>OriginPassword</label>
			<input type ="password" name ="OriginPassword">
			<label>NewPassword1</label>
			<input type ="password" name ="NewPassword1">
			<label>NewPassword2</label>
			<input type ="password" name ="NewPassword2">
			<input type ="submit" name="submit" value="submit">
		</form>
		<!-- form end  -->
	</div>
</div>