<div id="view-content">
	<div>
		<!-- error message start -->
			<?php
				if(isset($this->errormsg))
					echo $this->errormsg;
			?>
		<!-- error message end -->
	</div>
	
			<!-- 页码 -->
		<?php
		if($this->ifPP)
			echo '<div>
				<form action="/Un-Checked-Problem/Submit" method=get>
					<input type=submit value=SubmitProblem>
				</form>
			</div>';
		else
			echo '<div>';
			if($this->Page_Num)
			{
				for($i=1;$i<=$this->Page_Num;$i++)
				{
					echo '<a href="/Browse-Problem/Unchecked?page=',$i,'">',$i,'</a> ';
				}
			}
			echo '</div>';
		?>
	<div>
		<!-- result start -->
		
	<table id="mytable" cellspacing="0" 	>
		<caption></caption>
		<tr>
			<th scope="col" width=15%>题目ID</th>
		<?php
			if(!$this->ifPP)
				echo '<th scope="col" width=15%>上传者</th>'
		?>
			<th scope="col" width=45%>题目标题</th>
			<th scope="col" width=15%>题目状态</th>
		</tr>	
	<?php
		if($this->Result)
		{
			$line=1;
			foreach($this->Result as $key2=>$row)
			{
				echo "<tr>";
				foreach($row as $key=>$coloum)
				{
					if(is_integer($key))
					{	
						if($line%2)
							echo '<th scope="row" class="spec">';
						else
							echo '<th scope="row" class="specspecalt">';
						if($key==0)
						{
							if($this->ifPP)
							{
								echo '<a href="/Un-Checked-Problem/Update?up_id=';
							}
							else
								echo '<a href="/Un-Checked-Problem/Judge?up_id=';
							echo stripslashes($coloum).'">'.stripslashes($coloum);
							echo '</a>';
						}
						else
							echo str_replace("\n","<br>",stripslashes($coloum));						
						echo "</th>";
					}
				}
				$line++;
				echo "</tr>";
			}
		}
		else
			echo '<tr>
				<th scope="row" class="spec">NULL</th>
				<th scope="row" class="spec">NULL</th>
				<th scope="row" class="spec">NULL</th>
				<th scope="row" class="spec">NULL</th>
				</tr>';
	?>
	</table>
		<!-- result end -->
	</div>
	<div>
		<!--  -->
			
		<!--  -->
	</div>
</div>