
<div id="view-content">
	
	<div>
		<!-- errormsg -->
		<?php 
			if(isset($this->errormsg))
				echo $this->errormsg;
		?>
		<!-- errormsg end -->
	</div>
	<div>
		<!-- p_handoutstatus start -->
		<?php 
			if(isset($this->p_handoutstatus))
				echo $this->p_handoutstatus;
		?>
		<!-- p_handoutstatus end -->
	</div>
	<div>
		<!-- p_uploaderID start -->
		<?php 
			if(isset($this->p_uploaderID))
				echo $this->p_uploaderID;
		?>
		<!-- p_uploaderID end -->
	</div>
	<div>
		<!-- p_title start -->
		<?php 
			if(isset($this->p_title))
				echo $this->p_title;
		?>
		<!-- p_title end -->
	</div>
	<div>
		<!-- p_tlimt start -->
		<?php 
			if(isset($this->p_tlimt))
				echo $this->p_tlimt;
		?>
		<!-- p_tlimt end -->
	</div>
	<div>
		<!-- p_mlimt start -->
		<?php 
			if(isset($this->p_mlimt))
				echo $this->p_mlimt;
		?>
		<!-- p_mlimt end -->
	</div>
	<div>
		<!-- p_disc start -->
		<?php 
			if(isset($this->p_disc))
				echo $this->p_disc;
		?>
		<!-- p_disc end -->
	</div>
	<div>
		<!-- p_sample_input start -->
		<?php 
			if(isset($this->p_sample_input))
				echo $this->p_sample_input;
		?>
		<!-- p_sample_input end -->
	</div>
	<div>
		<!-- p_sample_output start -->
		<?php 
			if(isset($this->p_sample_output))
				echo $this->p_sample_output;
		?>
		<!-- p_sample_output end -->
	</div>
	<div>
		<!-- p_source start -->
		<?php 
			if(isset($this->p_source))
				echo $this->p_source;
		?>
		<!-- p_source end -->
	</div>
	<div>
		<!-- p_input_tips start -->
		<?php 
			if(isset($this->p_input_tips))
				echo $this->p_input_tips;
		?>
		<!-- p_input_tips end -->
	</div>
	<div>
		<!-- p_output_tips start -->
		<?php 
			if(isset($this->p_output_tips))
				echo $this->p_output_tips;
		?>
		<!-- p_output_tips end -->
	</div>
	<div>
		<!-- p_hint start -->
		<?php 
			if(isset($this->p_hint))
				echo $this->p_hint;
		?>
		<!-- p_hint end -->
	</div>
	<div>
		<!-- submit start -->
		<?
		if(!$this->ifPP && !$this->ifjudge)
		{
			echo '<form  action="" method="post">
					<input type="hidden" value="',$this->up_id,'"name="up_id"/>
					<input type="submit" value="Accept" name="decision"/>
					<input type="submit" value="Decline" name="decision"/>
			</form>';
		}
		echo '<a href="/Un-Checked-Problem">Return</a>';
		?>
		
		<!-- submit end -->
	</div>
</div>