<div id="view-content">
	<div id="title"><h2 class="title">
		<font size=6px color=#333399>上传题目</font>
	</h2></div>
	<div id="abc"></div>
	<div>
		<?php
			if(isset($this->errormsg))
				echo $this->errormsg;
		?>
	</div>
	<div>
		<!-- problem form start -->
		<?php
			if(isset($this->form_problem))
			{
				echo '<a href="/Un-Checked-Problem">return</a>';
				echo $this->form_problem;
			}
		?>
		<!-- problem form end -->
	</div>
</div>