<div id="view-content">

	<div id="title"><h2 class="title">
		<font size=6px color=#333399>修改上传题目</font>
	</h2></div>
	<div id="abc"></div>
	<div>
		<?php
			if(isset($this->errormsg))
				echo $this->errormsg;
			echo '<br><a href="/Un-Checked-Problem">Return</a>';
		?>
	</div>
	<div>
		<!-- problem form start -->
		<?php
			if(isset($this->form_problem))
			{
				echo $this->form_problem;
			}
		?>
		<!-- problem form end -->
	</div>
</div>