<br /><br />
<div id="view-content">
	<div>
		<!-- error message start -->
		<?php
			if(isSet($this->errormsg))
			{
				echo $this->errormsg,'<br>';
				echo '<a href="javascript:history.go(-1);">Return</a>';
			}
			if(isset($this->result))
				echo $this->result;
		?>
		<!-- error message end -->
	</div>
	<div>
		<!-- login form start -->
		<?php	
			if(isSet($this->formUser))
				echo $this->formUser;
		?>
		<!-- login form end -->
	</div>
</div>