	<div id="logo">
		<h1><a href="#">ECUST<sup></sup></a></h1>
		<h2>Online Judge System</h2>
	</div>
	<div id="menu">
		<ul>
			<li class="active"><a href="#">homepage</a></li>
			<li><a href="#">online judge</a></li>
			<li><a href="/BrowseProblem">problem set</a></li>
			<li><a href="browseproblemdetail.html">online status</a></li>
			<li><a href="#">auther</a></li>
			<li><a href="#">contact us</a></li>

		</ul>
	</div>