	<div id="logo">
		<h1><a href="#">ECUST<sup></sup></a></h1>
		<h2>Online Judge System</h2>
	</div>
	<div id="menu">
		<ul>
			<li class="active"><a href="/index">homepage</a></li>
			<li><a href="/Submit-Code">online judge</a></li>
			<li><a href="/Browse-Problem">problem set</a></li>
			<li><a href="/Online-Status">online status</a></li>
			<li><a href="/Un-Checked-Problem">unchecked set</a></li>
			<li><a href="#">auther</a></li>
			<li><a href="#">contact us</a></li>

		</ul>
	</div>