<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>ECUST Judge Online System</title>
<meta name="keywords" content="ECUST Judge Online" />
<meta name="description" content="ECUST Judge Online" />
<link href="/default.css" rel="stylesheet" type="text/css" />
<script src="/validate.js" type="text/javascript"></script>
<body>
<!-- start header -->
<div id="header">
	<?php echo $this->partial('header.phtml');?>
</div>
<!-- end header -->
<!-- start page -->
<div id="page">

<?php echo $this->layout()->content; ?>

</div>
<!-- end page -->
<!-- start footer -->
<div id="footer">
	<?php echo $this->partial('footer.phtml'); ?>
</div>
<!-- end footer -->
</body>
</html>
