
<div id="view-content"> <font size=4 color=#333399>Problem Status List</font>
		</p>
		<form method=get>
			Problem ID:
			<input type=text name=filter_problem_id size=8 value="">
			User Name:
			<input type=text name=filter_user_name size=15 value="">
			Result:
			<select size=1 name=filter_result>
				<option value=0>All</option>
				<option value=1>Accepted</option>
				<option value=2>Compile Error</option>
				<option value=3>Runtime Error</option>
				<option value=4>Time Limit Exceeded</option>
				<option value=5>Memory Limit Exceeded</option>
				<option value=6>Output Limit Exceeded</option>
				<option value=7>Wrong Answer</option>
				<option value=8>Code Length Exceeded</option>
				<option value=-1>System Error</option>
			</select>
			Language:
			<select size=1 name=filter_language>
				<option value=0>All</option>
				<option value=1>C</option>
				<option value=2>C++</option>
			</select>
			<input type=submit width=8 value=Go></form>
			
			<table id="mytable" cellspacing="0" 	>
				<caption></caption>
				<tr>
					<th scope="col" width=8%>Run ID</th>
					<th scope="col" width=10%>User</th>
					<th scope="col" width=6%>Problem</th>
					<th scope="col" width=20%>Result</th>
					<th scope="col" width=7%>Memory</th>
					<th scope="col" width=7%>Time</th>
					<th scope="col" width=7%>Language</th>
					<th scope="col" width=7%>Code Length</th>
					<th scope="col" width=17%>Submit Time</th>
				</tr>
		<!-- php start -->
		<?php
		if($this->Result)
		{
			foreach($this->Result as $key2=>$row)
			{
				echo "<tr>";
				foreach($row as $key=>$coloum)
				{
					
					if(!is_integer($key))
					{
						if($key2%2)
							echo '<th scope="row" class="spec">';
						else
							echo '<th scope="row"  class="specalt">';
							
						if($key =='user_name')
						{
							echo '<a href="/User/Userinfo?user_name=';
							echo str_replace("\n","<br>",stripslashes($coloum));
							echo '">'.str_replace("\n","<br>",stripslashes($coloum)).'</a>';
						}
						else if($key =='run_pid')
						{
							echo '<a href="/Browse-Problem/Detail?p_id=';
							echo str_replace("\n","<br>",stripslashes($coloum));
							echo '">'.str_replace("\n","<br>",stripslashes($coloum)).'</a>';
						}
						else
							echo str_replace("\n","<br>",stripslashes($coloum));
							
						echo "</th>";
					}
				}
				echo "</tr>";
			}
		}else
		echo 'no';
	?>
	<!-- php end -->
	</table>
</div>