
<div id="view-content"> <font size=6 color=#333399>提交状态</font>
		</p>
		<form method=get>
			题目ID:
			<input type=text name=filter_problem_id size=8 value="">
			用户名:
			<input type=text name=filter_user_name size=15 value="">
			结果:
			<select size=1 name=filter_result>
				<option value=0>All</option>
				<option value=1>Accepted</option>
				<option value=2>Compile Error</option>
				<option value=3>Runtime Error</option>
				<option value=4>Time Limit Exceeded</option>
				<option value=5>Memory Limit Exceeded</option>
				<option value=6>Output Limit Exceeded</option>
				<option value=7>Wrong Answer</option>
				<option value=8>Code Length Exceeded</option>
				<option value=-1>System Error</option>
			</select>
			语言:
			<select size=1 name=filter_language>
				<option value=0>All</option>
				<option value=1>GCC</option>
				<option value=2>G++</option>
			</select>
			<input type=submit width=8 value=Go></form>
			
			<table id="mytable" cellspacing="0" 	>
				<caption></caption>
				<tr>
				<th scope="col" width=8%>流水号</th>
				<th scope="col" width=10%>用户名</th>
				<th scope="col" width=10%>题目ID</th>
				<th scope="col" width=11%>结果</th>
				<th scope="col" width=10%>内存</th>
				<th scope="col" width=10%>时间</th>
				<th scope="col" width=7%>语言</th>
				<th scope="col" width=10%>代码长度</th>
				<th scope="col" width=13%>提交时间</th>
				</tr>
				
			<!-- 页码 -->
			<div>
			<?php
			if($this->Page_Num)
			{
				for($i=1;$i<=$this->Page_Num;$i++)
				{
					echo '<a href="/Online-Status?page=',$i,'">',$i,'</a> ';
				}
			}
			?>
			</div>	
		<!-- php start -->
		<?php
		if($this->Result)
		{
			foreach($this->Result as $key2=>$row)
			{
				echo "<tr>";
				foreach($row as $key=>$coloum)
				{
					
					if(!is_integer($key))
					{
						if($key2%2)
							echo '<th scope="row" class="spec">';
						else
							echo '<th scope="row"  class="specalt">';
							
						if($key =='user_name')
						{
							if($coloum!='NULL')
							{
								echo '<a href="/User/Userinfo?user_name=';
								echo str_replace("\n","<br>",stripslashes($coloum));
								echo '">'.str_replace("\n","<br>",stripslashes($coloum)).'</a>';
							}
							else
								echo $coloum;
						}
						else if($key =='run_pid')
						{
							if($coloum!='NULL')
							{
								echo '<a href="/Browse-Problem/Detail?p_id=';
								echo str_replace("\n","<br>",stripslashes($coloum));
								echo '">'.str_replace("\n","<br>",stripslashes($coloum)).'</a>';
							}
							else
								echo $coloum;
						}
						else if($key =='run_mcost')
						{
							if($coloum!='NULL')
							{
								echo str_replace("\n","<br>",stripslashes($coloum));
								echo ' KB';
							}
							else
								echo $coloum;
						}
						else if($key =='run_tcost')
						{
							if($coloum!='NULL')
							{
								echo str_replace("\n","<br>",stripslashes($coloum));
								echo ' MS';
							}
							else
								echo $coloum;
						}
						else if($key =='run_codel')
						{
							if($coloum!='NULL')
							{
								echo str_replace("\n","<br>",stripslashes($coloum));
								echo ' B';
							}
							else
								echo $coloum;
						}
						else
							echo str_replace("\n","<br>",stripslashes($coloum));
							
						echo "</th>";
					}
				}
				echo "</tr>";
			}
		}else
			echo '<tr>
				<th scope="row" class="spec">NULL</th>
				<th scope="row" class="spec">NULL</th>
				<th scope="row" class="spec">NULL</th>
				<th scope="row" class="spec">NULL</th>
				<th scope="row" class="spec">NULL</th>
				<th scope="row" class="spec">NULL</th>
				<th scope="row" class="spec">NULL</th>
				<th scope="row" class="spec">NULL</th>
				<th scope="row" class="spec">NULL</th>
				</tr>';
	?>
	<!-- php end -->
	</table>
</div>